### PR TITLE
use single -s arg with comma separated list of sauce browsers

### PR DESCRIPTION
**Pull request by frankiefu**
From @usergenic 's comment: https://github.com/Polymer/pwa-starter-kit/pull/155#pullrequestreview-128988381
See if this fixes the test issue.

### CODE REVIEW

**Comment by frankiefu** [comment]
🙏

**Comment by frankiefu** [comment]
@usergenic Tried to use comma separated list but it didn't work. Can you help us to figure out the right command to use.
Also noticed there was a polymer-cli release 3 days ago so maybe something was changed there.

**Comment by notwaldorf** [comment]
Now it's complaining these values don't match:
```
windows 10 microsoftedge 17,macos 10.13/safari@11 Tests failed: Unsupported OS/browser/version/device combo: OS: 'Windows 10', Browser: 'microsoftedge', Version: '17,macos 10.13/safari@11.', Device: 'unspecified'
```

**Comment by usergenic** [comment]
Tested fix by making `-s` "multiple: true"...
```
λ npx polymer test --module-resolution=node --npm -s 'windows 10/microsoftedge@17' -s 'macos 10.13/safari@11'
Creating Sauce Connect tunnel
Sauce Connect log: /tmp/wct118516-192250-1xi2lfy.9444f/sc.log
Sauce tunnel active: fdfcd716-a268-4c59-957e-bf4d92c66e2c
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
macos 10.13 safari 11    Beginning tests via http://localhost:8081/components/pwa-starter-kit/generated-index.html?cli_browser_id=1
[BABEL] Note: The code generator has deoptimised the styling of undefined as it exceeds the max of 500KB.
windows 10 microsoftedge 17 Beginning tests via http://localhost:8081/components/pwa-starter-kit/generated-index.html?cli_browser_id=0
macos 10.13 safari 11    Tests passed
windows 10 microsoftedge 17 Tests passed
Test run ended with great success

windows 10 microsoftedge 17 (16/0/0)    macos 10.13 safari 11 (16/0/0)
```

**Comment by frankiefu** [comment]
@usergenic Awesome! Thanks for looking into it.

**Comment by frankiefu** [comment]
@usergenic Thanks!

**Pull request closed without merging**
