### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by keanulee** [comment]
@abdonrd I was told that polymer-cli 1.7.6 works with Node 10. Can you verify and if so, remove the known issue from the README as well?

**Comment by abdonrd** [comment]
@keanulee right! It works now!

**Comment by abdonrd** [comment]
@keanulee we also should remove the `lit-element and lit-html have IE11 compatibility issues.`?

**Comment by keanulee** [comment]
No, there's still IE issues https://github.com/Polymer/lit-html/issues/368 https://github.com/Polymer/lit-html/issues/375

**Pull request merged**
