### PR TITLE
Add crossorigin=anonymous to push headers and update esm-amd-loader

### LINKED ISSUE #254: Console warnings about crossorigin and preloaded
There are a few warnings about crossorigin and preloaded.

screenshot 2018-10-28 at 12 57 19

> A preload for 'https://pwa-starter-kit.appspot.com/esm-bundled/src/components/my-view1.js' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
> `dispatch @ my-app.js:598`
> 
> The resource https://pwa-starter-kit.appspot.com/esm-bundled/src/components/my-app.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
> 
> The resource https://pwa-starter-kit.appspot.com/esm-bundled/src/components/my-view1.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### PR DESCRIPTION
**Pull request by keanulee**
Fixes #254. Deployed to https://pwa-starter-kit.appspot.com/

### CODE REVIEW

**Comment by abdonrd** [comment]
@keanulee @frankiefu Right now I can still see 2 warnings at https://pwa-starter-kit.appspot.com:

screenshot 2018-12-07 at 09 17 08

**Comment by frankiefu** [comment]
@abdonrd It seems to work for me.

screen shot 2018-12-07 at 9 39 01 am

Make sure you are on Chrome 71 and check the network panel in dev tools to make sure it's not using cached version.

**Comment by abdonrd** [comment]
I was in Chrome 70, it works with 71! Thanks @frankiefu!

**Comment by abdonrd** [comment]
@keanulee @frankiefu We also need to remove this `crossorigin `, right?

https://github.com/Polymer/pwa-starter-kit/blob/d53f4cc4e1263cf9c887ab93d79f302c7bcf00f9/index.html#L67

**Comment by keanulee** [comment]
I didn't see any in dev tools, so I think it doesn't matter if we remove it or not?

**Pull request merged**
