### PR TITLE
Use hostname 0.0.0.0 instead of 127.0.0.1

### PR DESCRIPTION
**Pull request by mindon**
Use hostname 0.0.0.0 instead of 127.0.0.1
To allow visiting server inside a docker container from outside

### CODE REVIEW

**Comment by AliMD** [comment]
Make it optional please not as default

For now, you can pass parameters with `--` like this
`npm start -- --hostname 0.0.0.0`

**Comment by notwaldorf** [comment]
Yeah, I don't think we should hardcode this in (it's the kind of change you should make on your checkout), but I've added a note about it in the wiki: https://github.com/Polymer/pwa-starter-kit/wiki/2.-Setup#run-the-app-in-development-mode

**Comment by abdonrd** [comment]
@notwaldorf review it, you write an extra ` --`:

`npm start -- --hostname 0.0.0.0 --port 4444`

**Comment by mindon** [comment]
thanks, mostly default is 0.0.0.0, but it seems 127.0.0.1 is better for security

**Comment by notwaldorf** [comment]
@abdonrd you need the extra `--` because you want to pass the arguments to `polymer serve` not the `npm start` script

**Comment by abdonrd** [comment]
@notwaldorf oh! I would swear it used to work without it. Thanks for the explanation!

**Comment by krumware** [comment]
For others, in your dockerfile you can use `CMD ["npm", "start", "--", "--hostname", "0.0.0.0", "--port", "8081"]` to serve the defaults

**Pull request closed without merging**
