### PR TITLE
IE11 compatible 

### PR DESCRIPTION
**Pull request by frankiefu**
- update to use lit-element#0.5.2 which has the [ShadyCSS fix](https://github.com/Polymer/lit-element/pull/102)
- use `role="main"` since `<main>` is not a thing in IE

### CODE REVIEW

**Comment by notwaldorf** [comment]
yeah i agree with @jsilvermist too. @frankiefu does that work for you?

**Comment by notwaldorf** [comment]
I don't understand what's wrong with the testssssss

**Comment by notwaldorf** [comment]
@usergenic the sauce tests don't seem to want to run anymore. i know y'all did a wct release recently, does this look related?

**Comment by frankiefu** [comment]
@notwaldorf and @jsilvermist I don't really have a strong opinion one way or the other. I will make the change.

**Comment by usergenic** [comment]
@notwaldorf we haven't released the new wct or wct-sauce libs yet afaict...  Not really sure what's going on here according to the logs.  Will look at more closely from desk in about 30 minutes if not resolved.

**Comment by notwaldorf** [comment]
@usergenic  Sure but this worked till very recently. Here's another /push build that passed: https://travis-ci.org/Polymer/pwa-starter-kit/jobs/389956508

```
> polymer test --module-resolution=node --npm -s 'windows 10/microsoftedge@17' -s 'macos 10.13/safari@11'
Creating Sauce Connect tunnel
...
```

**Comment by notwaldorf** [comment]
@frankiefu if we think this is just wct being weird and the PR is otherwise fine, then you should merge it!

**Comment by frankiefu** [comment]
Ok. Yeah let's merge this and if there is an actual issue with the wct args or something we can fix it in another PR. Let's 🙏

**Pull request merged**
