### PR TITLE
Typo fix in my-view2.js (build -> built)

### PR DESCRIPTION
**Pull request by sociallymellow**

### CODE REVIEW

**Comment by sociallymellow** [comment]
Signed! 🤗

**Comment by sociallymellow** [comment]
Not too familiar with the failed test but any information would be appreciated 😄

**Comment by notwaldorf** [comment]
The tests are failing because technically the screenshot has changed from the baseline. We can regenerate it after merging this PR, but let me talk to the team and figure out what our general approach will be for this.

**Comment by notwaldorf** [comment]
TL; DR: will fix the tests manually

**Pull request merged**
