### PR TITLE
Update template-no-redux with master

### PR DESCRIPTION
**Pull request by abdonrd**

### CODE REVIEW

**Comment by abdonrd** [comment]
@notwaldorf @frankiefu updated! 🎉

**Comment by frankiefu** [comment]
We should merge this [one](https://github.com/Polymer/pwa-starter-kit/pull/127/commits/03ef330ec82a59892b4abe3ac6909343e90ff1b3) too. Maybe in `my-app.js` do something like this:
```js
async _loadPage(page) {
  // If the page is invalid, set to 404. The is also a good spot to check
  // other location things like sub-path or query params.
  if (['view1', 'view2', 'view3'].indexOf(page) === -1) {
    page = 'view404';
  }

  this._page = page;

  switch(page) {
    case 'view1':
      await import('../components/my-view1.js');
      // Put code here that you want it to run every time when
      // navigate to view1 page and my-view1.js is loaded
      break;
    case 'view2':
      await import('../components/my-view2.js');
      break;
    case 'view3':
      await import('../components/my-view3.js');
      break;
    default:
      await import('../components/my-view404.js');
  }
}
```

**Comment by abdonrd** [comment]
Thanks @frankiefu, you are right! Updated!

**Comment by frankiefu** [comment]
@abdonrd Thanks for all the work!

**Comment by abdonrd** [comment]
@frankiefu happy to help!

**Comment by notwaldorf** [comment]
Yeah, thanks so much Abdon!!! <3

**Pull request merged**
